from pathlib import Path
import traceback
from dotenv import load_dotenv
load_dotenv()
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_core.prompts import PromptTemplate
from langchain_openai import ChatOpenAI
from langchain.chains.summarize import load_summarize_chain
long_text = """
Artificial intelligence has evolved dramatically over the past several decades, transforming from a niche academic pursuit into one of the most influential technologies shaping modern society. What began as simple rule-based systems capable of solving narrowly defined problems has grown into a vast ecosystem of machine learning models, neural networks, and large language models capable of understanding and generating human language with remarkable fluency. This evolution has not been linear; it has been marked by periods of rapid progress followed by so-called "AI winters," during which funding and interest waned due to unmet expectations. Nevertheless, the cumulative effect of decades of research has produced systems that can translate languages, recognize images, drive cars, and even write coherent essays on virtually any topic imaginable.

Natural language processing, or NLP, is one of the most important subfields of artificial intelligence, focused specifically on enabling computers to understand, interpret, and generate human language. Early NLP systems relied heavily on hand-crafted rules and dictionaries, which were labor-intensive to build and often failed to generalize to new domains or unexpected phrasing. The introduction of statistical methods in the 1990s marked a significant shift, allowing systems to learn patterns directly from large corpora of text rather than relying solely on human-defined rules. This statistical approach laid the groundwork for the machine learning revolution that would follow, eventually leading to the transformer-based models we see today.

The advent of deep learning in the 2010s fundamentally changed the landscape of NLP. Neural network architectures such as recurrent neural networks (RNNs) and long short-term memory networks (LSTMs) enabled models to capture sequential dependencies in text, improving performance on tasks like machine translation and speech recognition. However, it was the introduction of the Transformer architecture in 2017 that truly revolutionized the field. By relying on self-attention mechanisms instead of recurrence, Transformers allowed for much greater parallelization during training and could model long-range dependencies far more effectively than previous architectures. This innovation became the foundation for virtually all major language models developed in subsequent years.

Building on the Transformer architecture, researchers developed increasingly large language models, culminating in systems capable of few-shot and zero-shot learning across a wide variety of tasks. These models are trained on massive datasets scraped from books, websites, academic papers, and other textual sources, absorbing not only grammar and vocabulary but also factual knowledge, reasoning patterns, and stylistic nuances. The scale of these models, often measured in billions or even trillions of parameters, has been a key driver of their capabilities, though it has also raised concerns about computational cost, environmental impact, and accessibility for smaller organizations and researchers.

One of the most practically significant applications of large language models is text summarization. Summarization addresses a fundamental problem in the information age: the sheer volume of textual content being produced every day far exceeds any individual's capacity to read and digest it. Whether it is news articles, scientific papers, legal documents, medical records, or customer reviews, the ability to automatically distill lengthy text into a concise, accurate summary has enormous practical value across nearly every industry, from journalism and law to healthcare, finance, and technology sectors.

There are broadly two categories of summarization techniques: extractive and abstractive. Extractive summarization works by selecting a subset of existing sentences or phrases directly from the source text and stitching them together to form a summary. This approach has the advantage of preserving the original wording and factual accuracy, since no new content is generated. However, extractive summaries can sometimes feel disjointed or fail to capture nuanced relationships between ideas that span multiple sentences. Additionally, extractive methods may miss the most important information if it is not explicitly stated in a single sentence.

Abstractive summarization, in contrast, involves generating entirely new sentences that capture the essence of the source material, potentially using different words and sentence structures than the original text. This approach more closely resembles how a human might summarize a document, paraphrasing and condensing ideas rather than simply copying and pasting fragments. Abstractive methods have become increasingly viable with the rise of sequence-to-sequence models and, more recently, large language models that can generate fluent and coherent text. However, abstractive summarization is also more prone to hallucination, where the model generates plausible-sounding but factually incorrect information.

When dealing with documents that exceed the context window of a language model, a common strategy is to employ a map-reduce approach to summarization. In the "map" step, the long document is split into smaller chunks, and each chunk is summarized independently by the model. In the "reduce" step, these individual chunk summaries are combined and then summarized again, potentially through multiple iterations, until a final, cohesive summary is produced. This technique allows language models with limited context windows to effectively process documents of arbitrary length, making it invaluable for real-world applications.

The map-reduce summarization pattern is particularly well suited to frameworks like LangChain, which provide abstractions for chaining together multiple language model calls into a coherent pipeline. By defining a map prompt that instructs the model to summarize a chunk of text, and a reduce prompt that instructs the model to combine multiple summaries into one, developers can build robust summarization pipelines without needing to manually manage the complexity of chunking, batching, and aggregation. This abstraction greatly simplifies the development process and allows for rapid experimentation with different summarization strategies.

The implementation of map-reduce summarization involves several key decisions that can significantly impact the quality of the final output. First, the chunk size must be chosen carefully: chunks that are too small may lose important context, while chunks that are too large may exceed the model's context window. Second, the overlap between chunks can be used to ensure that important information spanning chunk boundaries is not lost. Third, the number of reduction iterations must be balanced against computational cost, as each iteration requires additional API calls and processing time.

Despite these advances, summarization remains a challenging problem, particularly when it comes to preserving factual accuracy across long documents. Language models can sometimes "hallucinate" details that were not present in the original text, introducing errors or fabrications into the summary. This is especially problematic in high-stakes domains such as medicine or law, where an inaccurate summary could lead to serious consequences. Researchers continue to develop techniques for improving the faithfulness of generated summaries, including retrieval-augmented generation, fact-checking modules, and reinforcement learning from human feedback.

Another important consideration in summarization is the trade-off between compression ratio and information retention. A highly compressed summary is easier and faster to read but risks omitting important details that could be crucial for understanding the full context. Conversely, a longer summary retains more information but may not save the reader significant time compared to reading the original document. Striking the right balance often depends on the specific use case: a headline generator might prioritize extreme brevity, while a legal document summarizer might prioritize completeness over conciseness.

Evaluation of summarization quality is itself a nontrivial problem that has received significant attention from researchers. Automated metrics such as ROUGE and BLEU compare generated summaries against reference summaries by measuring overlapping words or phrases, but these metrics often fail to capture semantic similarity or factual correctness. More recent evaluation approaches leverage language models themselves to judge the quality of summaries, assessing criteria such as coherence, relevance, fluency, and faithfulness to the source material. Human evaluation remains the gold standard, though it is costly and time-consuming to conduct at scale.

Beyond summarization, the broader field of natural language generation encompasses a wide range of applications, including machine translation, dialogue systems, question answering, paraphrase generation, and creative writing assistance. Each of these applications presents its own unique challenges and requires careful consideration of factors such as context length, domain specificity, and the desired balance between creativity and factual grounding. As language models continue to improve, the boundaries between these different applications are becoming increasingly blurred, with a single foundation model often capable of performing many of these tasks simultaneously with minimal task-specific fine-tuning.

The economics of language models has also become an important consideration for practitioners and organizations. API-based models such as OpenAI's GPT-4 offer convenience and state-of-the-art performance but come with ongoing costs that can accumulate quickly for high-volume applications. Open-source models, while free to use, require substantial computational resources to run and may lag behind the latest proprietary models in terms of performance. Organizations must carefully evaluate these trade-offs based on their specific requirements, budget constraints, and performance targets.

Looking toward the future, researchers are exploring ways to make language models more efficient, more interpretable, and more aligned with human values and intentions. Techniques such as model distillation, quantization, and sparse attention mechanisms aim to reduce the computational footprint of large models without sacrificing too much performance. Meanwhile, efforts in interpretability research seek to better understand the internal representations and decision-making processes of these models, which remain largely opaque despite their impressive capabilities. Understanding these mechanisms could lead to more trustworthy and predictable systems.

The environmental impact of training and running large language models has become an increasingly pressing concern. The energy required to train models like GPT-4 is substantial, resulting in significant carbon emissions. Additionally, the ongoing computational cost of inference (running the model on new inputs) means that widespread deployment of these models could have notable environmental consequences. Researchers are working on more efficient architectures and training procedures to minimize this impact while maintaining model performance.

One emerging area of research is prompt engineering, which involves carefully crafting the input prompts to language models to elicit the desired behavior. It turns out that small changes in how a question is phrased or contextualized can significantly impact the quality of the model's response. This has led to a new discipline where practitioners spend considerable time experimenting with different prompt formulations to achieve optimal results. While some view this as a temporary phenomenon that will be superseded by better model architectures, others argue that prompt engineering represents a fundamental aspect of working with language models.

Chain-of-thought prompting is another important technique that has emerged from recent research. By explicitly asking models to explain their reasoning step-by-step before providing a final answer, researchers have found that models often produce more accurate and reliable responses, particularly on complex reasoning tasks. This technique taps into an interesting property of language models: while they can hallucinate plausible-sounding but incorrect information, when forced to show their work, they are often more careful and accurate. This suggests that the problem may not be a lack of reasoning ability but rather a lack of sufficient motivation or structure to apply that reasoning consistently.

Fine-tuning has remained an important technique for adapting pre-trained language models to specific domains or tasks. While the impressive performance of large language models on diverse tasks through few-shot learning has reduced the need for fine-tuning in many cases, there are still scenarios where fine-tuning on domain-specific data can yield significant improvements. Additionally, for cost-sensitive applications or scenarios where latency is critical, fine-tuned smaller models may outperform using a large general-purpose model through an API.

The rise of multimodal models that can process both text and images represents another frontier in artificial intelligence. These models open up new possibilities for applications such as image captioning, visual question answering, and document understanding. The combination of visual and textual information can provide richer context for tasks like summarization, where the visual layout or diagrams in a document might convey important information not captured by the text alone.

Transfer learning has been a cornerstone of progress in machine learning, and language models represent perhaps the most successful application of this principle at scale. By pre-training on vast quantities of text, models learn general linguistic knowledge that transfers effectively to many downstream tasks. This means that practitioners can often achieve good performance with minimal task-specific data, democratizing access to powerful AI systems for organizations and individuals with limited resources.

The question of whether language models possess true understanding or are merely performing statistical pattern matching remains philosophically interesting but perhaps less practically important. Regardless of the underlying mechanism, these systems have proven remarkably useful for a wide range of real-world applications. That said, understanding the capabilities and limitations of these systems is crucial for deploying them responsibly and avoiding overconfidence in their outputs.

Bias and fairness in language models have become topics of significant concern and study. Training data scraped from the internet inevitably contains societal biases, and models trained on this data can perpetuate or amplify these biases. This is particularly problematic when language models are used for high-stakes decisions affecting individuals, such as resume screening, loan applications, or criminal sentencing. Mitigating these issues requires careful attention to training data selection, explicit bias correction techniques, and ongoing monitoring of model outputs.

Copyright and intellectual property concerns have also emerged around large language models. Some of the training data used to build these models may include copyrighted works without explicit permission, raising questions about whether such use constitutes fair use or infringement. Additionally, there are questions about whether models can generate substantially similar outputs to their training data, potentially violating copyright. These legal and ethical questions remain largely unresolved and will likely be shaped by ongoing litigation and regulatory developments.

The concentration of language model development among a few well-funded organizations has raised concerns about accessibility and diversity in AI development. As the computational requirements for training state-of-the-art models have grown exponentially, the barrier to entry for new researchers and organizations has increased dramatically. This has led to calls for more open-source model development and for supporting smaller organizations in training and deploying language models.

Looking at the integration of language models into existing software systems, we see that APIs like those provided by OpenAI have made it relatively straightforward to incorporate powerful language capabilities into applications. Frameworks like LangChain have further simplified this integration by providing abstractions that handle common patterns and workflows. This democratization of language model access has enabled developers to rapidly prototype and deploy new applications that would have been impossible just a few years ago.

The future trajectory of language models remains uncertain but exciting. Some researchers envision continued improvements through scaling, while others argue that fundamental architectural innovations are necessary to achieve artificial general intelligence. Some believe that combining language models with other AI techniques such as reinforcement learning, symbolic reasoning, and knowledge graphs may be necessary to achieve more robust and reliable systems. Regardless of the specific path taken, it is clear that language models will continue to play an increasingly central role in AI development and real-world applications.

Ultimately, the goal of much of this research is not simply to build bigger and more powerful models, but to build systems that are genuinely useful, trustworthy, and beneficial to the people who rely on them. Summarization technology, in particular, holds great promise for helping individuals and organizations manage the overwhelming flow of information in the modern world, freeing up time and attention for deeper analysis, decision-making, and creative work. As these tools continue to mature and become more sophisticated, they are likely to become an indispensable part of how we read, write, process, and understand information in our daily lives, fundamentally reshaping knowledge work and information consumption.

In many organizations, the adoption of language models begins with a small pilot project and grows gradually as teams discover new use cases. The first wins are often surprisingly simple, such as automating repetitive writing tasks, drafting support responses, or generating summaries from dense documentation. Once people experience the benefits, interest spreads quickly across departments and the range of applications expands dramatically. This incremental adoption pattern often proves more sustainable than trying to deploy an ambitious system all at once.

A major reason for this success is that modern language models are often used as assistants rather than as fully autonomous agents. They help humans write, analyze, search, and structure information, while still leaving the final judgment to a person. That collaborative model reduces risk and makes it easier to integrate AI into sensitive workflows. It also helps organizations build trust in the technology over time instead of expecting perfect behavior from the beginning.

Another important theme in the evolution of language models is the growing role of retrieval systems. A model that can access external documents at inference time is often more accurate than one that must rely solely on memorized knowledge. Retrieval-augmented generation combines the flexibility of language models with the precision of curated knowledge sources. In this setup, the model searches for relevant evidence, grounds its response in that evidence, and then produces a final answer that is both fluent and better supported.

This hybrid approach is especially valuable in domains where factual accuracy matters deeply, such as legal research, technical support, medical documentation, and compliance review. In those settings, a hallucinated answer can be costly or even dangerous. Retrieval systems help reduce that failure mode by making the model cite or leverage relevant documents before writing a response. The result is often a more trustworthy system, even if the underlying model remains imperfect.

The idea of human-in-the-loop systems has become increasingly important as AI tools move from experimentation into production. In these systems, humans remain involved in reviewing, correcting, and validating model outputs before they are used for high-stakes decisions. This does not eliminate the value of automation, but it places safeguards around it. By combining model speed with human oversight, organizations can achieve a better balance between efficiency and reliability.

As language models become more capable, the distinction between writing, coding, and data analysis is also becoming less rigid. A single model can now help draft code snippets, explain errors, summarize logs, generate documentation, and assist in data transformation. This convergence of capabilities makes the tools more powerful, but it also means that users increasingly need broad digital literacy rather than narrow expertise in a single domain. The ability to ask good questions and critically evaluate outputs is becoming as important as the technical skill of writing code.

The rise of agentic workflows is another development that has captured attention in recent years. Instead of responding to a single prompt, a system can now be designed to break a task into steps, gather information, choose tools, and revise its approach over time. This kind of orchestration allows language models to handle more complex tasks such as planning, research, and multi-step automation. It also introduces new challenges around reliability, error propagation, and the need for clear boundaries between machine autonomy and human control.

One of the most exciting areas of progress is the combination of language models with symbolic reasoning and structured knowledge. Language models are exceptionally good at processing text, while symbolic systems are often better at consistency, formal logic, and rule-based decision-making. When these approaches are combined, the resulting system can be more robust than either approach alone. This hybrid strategy is becoming increasingly relevant for applications that require both flexibility and precision.

Another practical concern is latency, or how quickly a model can return an answer. In real applications, users often care just as much about response speed as about raw quality. A powerful model that takes too long to respond may be less useful than a slightly weaker model that is nearly instantaneous. This has driven interest in smaller models, distilled versions, and optimized inference pipelines. The goal is not always to maximize quality at any cost, but to reach the best quality-speed trade-off for the specific task.

Security and privacy are also becoming central topics in the deployment of language models. Many organizations are concerned about sensitive data being sent to external APIs or exposed through prompt logs and model outputs. These concerns have prompted stronger emphasis on data handling policies, on-premises deployments, and techniques for minimizing the amount of information that must be shared with a model. Responsible use increasingly requires both technical safeguards and organizational governance.

The discussion around open models has also intensified, especially as the cost of proprietary access becomes a barrier for many researchers and startups. Open-source alternatives make it easier to inspect model weights, adapt architectures, and fine-tune systems for local needs. They also foster innovation by allowing the broader community to study and improve the technology. Although open models may not always match proprietary systems in raw quality, they play a crucial role in making AI more accessible and more transparent.

Another topic that continues to grow in importance is the evaluation of model behavior beyond simple benchmark scores. A model that performs well on standard tests may still fail in realistic settings where instructions are ambiguous, context is noisy, or users are frustrated. For that reason, practitioners increasingly evaluate systems through task-based testing, user studies, and scenario simulations. This shift reflects a more practical understanding of what successful AI deployment really looks like.

The cultural impact of language models should also not be underestimated. These tools are changing how people write, how students learn, how journalists research stories, and how businesses communicate with customers. They are also raising new questions about authorship, originality, and the boundaries between assistance and automation. As these tools become more embedded in everyday workflows, society will need to define norms for their use in a way that preserves human agency and creativity.

From an educational perspective, language models can act as tutors, brainstorming partners, and study aids. They can explain difficult concepts in simpler terms, offer examples, and adapt their level of detail to a learner's needs. At the same time, they can encourage overreliance if students treat them as substitutes for thinking rather than supports for learning. The educational challenge is therefore not only to use the tools effectively, but to teach people how to use them responsibly.

The business case for language models is also evolving from simple automation to strategic augmentation. Rather than replacing employees outright, these systems often enhance productivity by accelerating drafting, analysis, and coordination work. That makes them particularly attractive in knowledge-intensive industries where time is precious and expertise is scarce. When deployed thoughtfully, they can multiply human effort rather than merely reduce labor costs.

The continuing progress of language models will likely depend on several parallel trends, including better training data quality, improved architectures, more efficient hardware, and stronger alignment methods. None of these factors alone is sufficient, but together they create a path toward systems that are both more capable and more dependable. The next decade may be defined less by a single breakthrough and more by the steady integration of many incremental improvements.

Even as models become more powerful, the need for clear interfaces and thoughtful design remains essential. A model can be impressive in isolation and still fail when placed inside a confusing workflow. Good user experience, careful prompt design, and transparent error handling are therefore just as important as model quality. The best systems are often those that combine advanced capabilities with disciplined product design.

In the long term, the central question may not be whether language models can perform impressive tasks, but whether they can be used in ways that are beneficial, fair, and sustainable. That broader framing invites researchers, developers, and policymakers to think beyond raw capability and consider the social consequences of deployment. It is a reminder that technical progress must be accompanied by ethical judgment and practical accountability.

"""

splitter = RecursiveCharacterTextSplitter(
    chunk_size=250, chunk_overlap=70
)

parts = splitter.create_documents([long_text])

llm = ChatOpenAI(model_name="gpt-4", temperature=0)

chain_summarize = load_summarize_chain(llm, chain_type="map_reduce", verbose=True)

output_path = Path(__file__).with_name("resumo_summarizacao.txt")

try:
    summary = chain_summarize.invoke({"input_documents": parts})

    if isinstance(summary, dict):
        final_text = summary.get("output_text") or summary.get("text") or str(summary)
    else:
        final_text = str(summary)

    output_path.write_text(final_text, encoding="utf-8")
    print(summary)
    print(f"\nResumo salvo em: {output_path}")
except Exception as exc:
    error_text = f"Erro ao gerar resumo:\n{type(exc).__name__}: {exc}\n\n{traceback.format_exc()}"
    output_path.write_text(error_text, encoding="utf-8")
    print(error_text)
